	.ORIG X3000

	AND R7, R7, #0
	LD R1, A

AAA	LDR R0, R1, #0 ; R1[A] IS LOADED TO R0
	ADD R2, R0, R0 ; R2 CONTAINS R0*2

	ADD R0, R0, #1 ;  FLAG
	BRz BBB ; IF R0 + 1 IS 0, THAT MEANS WE HIT OUR FLAG

	STR R2, R1, #0 ; STORE R2, WHICH IS OUR NUMBER * 2, INTO R1 WITH AN OFFSET OF 0, IE DOUBLE THE NUMBER AND STORE IT BACK INTO THE SAME PLACE
	ADD R1, R1, #1 ;  R1 = R1+1, IE INCREMENT LOOP SO A[0] = A[1] FOR OUR NEXT ITERATION

	BR AAA ;  GO BACK TO AAA

BBB 	HALT

A	.FILL x3100

	.END